baseURL = "/"
title = "UPSC GQ"
theme ="basic"
languageCode = "en-us"
googleAnalytics = "UA-XXXXXXXXX-X"
enableEmoji = true 
copyright = "Â© UPSC GQ 2020. Made by <a href="https://twitter.com/AsadAdvik">@asadadvik</a>"
description = "free resource list for UPSC CSE"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":tada:"
  # change this!
  twitter = "asadadvik"

[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "blog"
  url = "post/"

[[params.menu]]
  name = "post series"
  url = "series/"
  

[[params.menu]]
  name = "about"
  url = "about/"
  

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true